#!/usr/bin/env python3
"""Shapes declared by `rudi193-cmd/yggdrasil-training-data` — rung 34.

    python scripts/corpus/extract_yggdrasil.py --repo /workspace/yggdrasil-training-data \
        --out data/corpus/yggdrasil.db

The only source in the chronology that is **already a pair corpus**. Sixteen
JSONL files, 65 MB, in the shape `prompt` / `chosen` / `rejected` — which is
this project's own subject written in another vocabulary four months earlier.

**Most of it is declined, and the reason is the whole point.** Of roughly 30,000
rows:

| | rows | what it is |
|---|---|---|
| `slm_baseline`, `slm_positive`, `slm_voice`, `slm_negative` | ~28,400 | harvested from `SESSION_*` transcripts — Claude Code and claude.ai exports |
| `sft_v8` (`llm_generated`), `slm_refusal` | 566 | generated by a model |
| `slm_governance`, `sft_v8` (`handcrafted`), `corrections/` | **130** | **written by the operator** |

The 28,400 are instruction/response pairs whose *response* side is an
assistant's output, captured from conversations. Importing them would file
model output under this operator's name at a scale that would make it 60% of
the entire corpus — §6.59's error (a population that looks like the author's and
is not) at the largest scale it could possibly occur. They are counted and
refused.

**What is taken:**

* **governance** — 48 rows (26 hand-written QA, 22 lifted from documents), about how the fleet
  should behave.
* **handcrafted** — the 50 rows of `sft_v8` marked `handcrafted`, against 488
  marked `llm_generated` in the same file. The file itself records which is
  which; nothing here is inferred.
* **correction** — 32 rows from `corrections/`, and these are the most on-subject
  material in one hundred and five repositories: a human correcting an agent
  mid-session, with the rejected utterance, an error type
  (`ambiguous`, `drift_from_mandate`) and `correction_absorbed` recording
  whether the agent took it.

**On the 880 rejections this repository holds, which are not imported as
rejections.** `dpo_pairs.jsonl` and `corrections/` carry a `rejected` field —
real answers a real person turned down. Nestor has verbs for exactly that
(`reject_match`, `reject_pair`) and `CLAUDE.md` reserves them for a human's no.
The operator made these decisions; but *writing them into a store* is still an
act, and it is theirs. So every row lands as a **draft**, with the rejected text
and its error type preserved in `reason` where a curator can see them, and the
question of promoting them to real rejections goes to `nestor.ui`.

**The source is private.** Store to gitignored `data/`; nothing committed.
"""
from __future__ import annotations

import argparse
import collections
import json
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2]))

import common                                                    # noqa: E402
import provenance                                                # noqa: E402

from nestor.sqlite_store import SqliteStore                      # noqa: E402

AUTHORED = {"governance", "governance-doc", "handcrafted"}
# `source_type` is not sufficient on its own. `slm_refusal.jsonl` labels 78 rows
# `governance` while their `source` reads `refusal-synthetic-77HE` — synthetic
# rows wearing an authored type. Taking the type at its word would have imported
# them as the operator's writing. Both fields must agree.
GENERATED = ("synthetic", "generated")


def rows(path: pathlib.Path):
    for line in path.open(encoding="utf-8"):
        line = line.strip()
        if not line:
            continue
        try:
            yield json.loads(line)
        except json.JSONDecodeError:
            continue


def authored(root: pathlib.Path) -> tuple[list[tuple], collections.Counter]:
    """instruction → response, only where the file says a human wrote it."""
    out, declined = [], collections.Counter()
    for path in sorted(root.glob("*.jsonl")):
        for d in rows(path):
            kind = d.get("source_type") or "-"
            src, tgt = d.get("instruction"), d.get("response")
            if not (src and tgt):
                continue
            src_field = str(d.get("source", "")).lower()
            if kind not in AUTHORED or any(g in src_field for g in GENERATED):
                label = kind if kind not in AUTHORED else f"{kind}/generated"
                declined[f"{path.name}: {label}"] += 1
                continue
            why = f"source: {d.get('source', '?')}"
            if d.get("btr_dims"):
                why += f" | dims: {d['btr_dims']}"
            out.append((src[:400], tgt[:900], why, path, kind))
    return out, declined


def corrections(root: pathlib.Path) -> list[tuple]:
    """A human correcting an agent mid-session, with what was turned down."""
    out = []
    for path in sorted((root / "corrections").glob("*.jsonl")):
        for d in rows(path):
            prompt, chosen = d.get("prompt"), d.get("chosen")
            if not (prompt and chosen):
                continue
            why = f"error: {d.get('_error_type', '?')}"
            if d.get("_agent"):
                why += f" | agent: {d['_agent']}"
            why += f" | absorbed: {d.get('correction_absorbed')}"
            if d.get("rejected"):
                why += f" | REJECTED: {' '.join(str(d['rejected']).split())[:400]}"
            out.append((prompt[:400], chosen[:900], why, path, d.get("_error_type", "")))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--repo", required=True)
    ap.add_argument("--name", default="yggdrasil")
    ap.add_argument("--out", required=True)
    args = ap.parse_args()

    root = pathlib.Path(args.repo).resolve()
    if not common.require_checkout(root):
        return 1
    out = pathlib.Path(args.out).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    if out.exists():
        out.unlink()

    origin = provenance.Origin(args.name, root, __file__)
    taught, declined = authored(root)
    plan, stock_declined, symbols, defined = common.standard(root)
    plan = [("authored", taught, "question", "answer"),
            ("correction", corrections(root), "prompt", "correction"),
            *plan]
    declined.update(stock_declined)

    store = SqliteStore(str(out))
    store.memory_init()
    try:
        common.load(store, plan, origin, declined, root)
        print(f"\n  declined {sum(declined.values())} row(s) as not the operator's "
              f"declarations — transcript-derived or model-generated")
    finally:
        store.close()
    print(f"\n  store: {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
