#!/usr/bin/env python3
"""Feed jeles' institutional source registry in — a source, and what it claims.

    python scripts/feed_jeles_sources.py --repo /path/to/jeles
    python scripts/feed_jeles_sources.py --repo … --keep DIR
    python scripts/feed_jeles_sources.py --repo … --findings docs/jeles-source-findings.md

Second repository fed into this store. `jeles/sources.py` declares
``SOURCES: dict[str, dict]`` — 65 institutions, each with a display name, a list
of subject ``domain`` tags, a ``key_required`` flag and an allow-list of
``hosts``. ``route_sources()`` picks which to fan a query across by matching its
domain tags.

**Why this corpus and not another.** The registry's own comment says
``tests/test_sources.py`` pins each declaration against actual behaviour, "so
the two cannot drift apart silently" — and that is true of the parts a test can
reach. ``key_required`` is checkable: call it without a key and see whether it
abstains. ``hosts`` is checkable: watch where it connects.

The ``domain`` list is not. *Is OpenAlex a good source for the humanities?* is
an editorial judgment about a routing decision, and no test in any repository
can make it. It is also the field that decides what a user's question actually
reaches. That is the row: **source → the subjects it claims to serve**, sealed
when a person has agreed the claim is right.

**And it is the first corpus here where a seal genuinely decays.** A clause does
not stop being the clause. An institution's API changes, moves, starts requiring
a key, or stops covering a subject it used to. ``docs/seal-staleness-and-quorum.md``
is the open question in this repo about exactly that, and this is the first
material that puts weight on it: *verified once, served forever* is the pitch,
and a source verified in May may be wrong by August without anybody touching the
row. Nothing here resolves that. It supplies the case.

**Read by parsing, never importing** — same rule as
``scripts/feed_willow_constitution.py``. jeles is stdlib-only and safe to
import, which is exactly why the rule has to be about the rule rather than about
this repository being trustworthy.

**Everything lands as a draft**, and the default `StringMatcher` is used
deliberately: the source key is unique by construction (it is a dict key), so
this corpus needs no custom matcher and inventing one would be ceremony.
"""
from __future__ import annotations

import argparse
import ast
import collections
import os
import pathlib
import shutil
import sys
import tempfile

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1]))

os.environ.setdefault("NESTOR_SEAL_KEY", "feed-fixture-key-not-a-secret")

from nestor import cascade, memory, storage          # noqa: E402
from nestor.sqlite_store import SqliteStore          # noqa: E402

DOMAIN = "source"
TARGET = "serves"
ORIGIN = "jeles:sources"

BOLD, DIM, GREEN, AMBER, RED, OFF = (
    "\033[1m", "\033[2m", "\033[32m", "\033[33m", "\033[31m", "\033[0m")


def format_findings(
    *,
    n_sources: int,
    n_keyed: int,
    twins: dict[tuple, list[str]],
    shared: list[tuple[str, int]],
    n_hosts: int,
    alone: list[str],
    n_subjects: int,
) -> str:
    """The feeder's measured findings as plain Markdown.

    Every section here corresponds to a block of stdout output in ``main()``.
    This function exists because, before it did, the findings lived only in
    that output: every reader re-derived or misread them privately.  The
    problem — and the misreading that proved it — is recorded in IDEAS 6.104.
    """
    lines: list[str] = []
    a = lines.append

    a("# Jeles source registry — measured findings")
    a("")
    a("*Generated by `scripts/feed_jeles_sources.py --findings`.*")
    a("*Re-run the script against a jeles checkout to regenerate.*")
    a("")
    a(f"Registry declares **{n_sources} institutions**.")
    a(f"`key_required` is checkable and {n_keyed} declare it; "
      "hosts are checkable. Subjects are not.")
    a("")

    # --- identical subject tuples ---
    a("## Sources declaring identical subjects")
    a("")
    a("`route_sources()` cannot prefer one over the other when two sources")
    a("declare the same subject tuple.")
    a("")
    if not twins:
        a("None.")
    else:
        a("| Sources | Subjects |")
        a("|---------|----------|")
        for domains, keys in sorted(twins.items()):
            a(f"| {', '.join(keys)} | {', '.join(domains)} |")
    a("")

    # --- host overlap ---
    a("## Hosts named by more than one source")
    a("")
    a("The egress allow-list is per source; the host is not.")
    a("")
    if shared:
        a("| Count | Host |")
        a("|------:|------|")
        for host, count in shared[:6]:
            a(f"| {count} | {host} |")
        a("")
    a(f"{len(shared)} shared host(s) of {n_hosts} total. "
      "The allow-list is tight, which is the honest reading. "
      "Granting one source's reach does grant a host others use, "
      "but at this ratio that is a note, not a finding.")
    a("")

    # --- single-sourced subjects ---
    a("## Subjects with exactly one source")
    a("")
    a(f"**{len(alone)} of {n_subjects}** subjects are served by a single "
      "institution. A query tagged to one of these fans out to one source, "
      "which cannot clear a two-source corroboration bar by construction.")
    a("")
    if alone:
        a(", ".join(alone) + ".")
    else:
        a("None.")
    a("")

    # --- corroboration hypotheses ---
    a("## Corroboration — measured hypotheses")
    a("")
    a("Both hypotheses below were raised in earlier runs as unmeasured. "
      "Both have now been resolved, and neither resolved the way it was "
      "written.")
    a("")
    a("### Hypothesis 1: single-sourced subjects struggle to clear the "
      "corroboration bar")
    a("")
    a("**Status: CONFIRMED, but the stated reason was wrong.**")
    a("")
    a("The difficulty is not because coverage is narrow. "
      "`jeles.verify._identity` reads `citation['source']` first, and "
      "`sources._result` puts the registry key there across all 69 call "
      "sites (65 constants). The per-record institution each adapter "
      "assembles is therefore never counted: one adapter returning five "
      "different institutions counts as one. This **understates** "
      "corroboration.")
    a("")
    a("Filed as jeles#53.")
    a("")
    a("### Hypothesis 2: nine sources listing doi.org collapse under "
      "`registrable_domain()`")
    a("")
    a("**Status: FALSIFIED — the error runs the opposite direction.**")
    a("")
    a("The concern was that nine sources list `doi.org` and "
      "`registrable_domain()` would collapse them, letting nine "
      "institutions corroborate as one. That cannot happen: the site is "
      "only a fallback for a citation with no label, and `_result` always "
      "sets one. Two `doi.org` citations from different adapters keep "
      "distinct keys (`openalex`, `core`).")
    a("")
    a("The real error runs the other way: two adapters carrying the same "
      "institution read as corroborated. This **overstates** corroboration.")

    return "\n".join(lines) + "\n"


def extract(path: pathlib.Path) -> dict | None:
    """The ``SOURCES`` literal, by parsing. No import, no execution.

    ``None`` means *this could not be read* — no ``SOURCES`` binding, or one
    whose value is not a literal. ``{}`` means *it was read and declares
    nothing*. Those are different facts and an earlier version returned ``{}``
    for both, so a registry the parser could not understand was reported in the
    same words as an empty one. That is the conflation this package exists to
    refuse, made by a script in this package, and it was found by running the
    feeders against an empty repository rather than by reading them.
    """
    tree = ast.parse(path.read_text(encoding="utf-8"))
    for node in tree.body:
        target = None
        value = None
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            target, value = node.target.id, node.value
        elif isinstance(node, ast.Assign) and len(node.targets) == 1 \
                and isinstance(node.targets[0], ast.Name):
            target, value = node.targets[0].id, node.value
        if target == "SOURCES" and value is not None:
            try:
                got = ast.literal_eval(value)
            except (ValueError, SyntaxError, TypeError):
                return None
            return got if isinstance(got, dict) else None
    return None


def claim(key: str, spec: dict) -> tuple[str, str]:
    """``(source_text, target_text)`` for one registry entry."""
    name = spec.get("name") or key
    domains = ", ".join(spec.get("domain") or []) or "(no subjects declared)"
    return (f"{key} — {name}", domains)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--repo", required=True, help="a jeles checkout")
    ap.add_argument("--keep", default="", help="leave the store behind here")
    ap.add_argument("--findings", default="",
                    help="write measured findings to this Markdown file")
    args = ap.parse_args()

    path = pathlib.Path(args.repo) / "jeles" / "sources.py"
    if not path.exists():
        print(f"{RED}no jeles/sources.py under {args.repo}{OFF}")
        # The absent branch had the right exit code and the wrong words. Twelve
        # lines below, the *unparseable* branch says "I could not look" and
        # explains that it is not the same as an empty one — this one said
        # nothing, so the two refusals this file exists to distinguish were
        # themselves distinguishable only by exit code. Found by
        # tests/test_corpus_readers_fail_closed.py on its first run, which is
        # the drift that gate was written for.
        print(f"   {DIM}'I could not look' — refusing rather than reporting "
              f"zero institutions.{OFF}")
        return 1
    sources = extract(path)
    if sources is None:
        print(f"{RED}could not read a SOURCES mapping out of {path}{OFF}")
        print(f"   {DIM}Not the same as an empty one — this is 'I could not "
              f"look', and it refuses rather than reporting zero.{OFF}")
        return 1
    if not sources:
        print(f"\n{BOLD}jeles sources → nestor{OFF}")
        print(f"   {AMBER}the registry was read and declares 0 institutions{OFF}")
        print(f"   {DIM}A true empty, not a failure. Said in different words "
              f"from 'could not read' on purpose.{OFF}\n")
        return 0

    work = pathlib.Path(args.keep) if args.keep else pathlib.Path(
        tempfile.mkdtemp(prefix="nestor-feed-jeles-"))
    work.mkdir(parents=True, exist_ok=True)
    cascade.set_ledger_path(str(work / "ledger.jsonl"))
    store = SqliteStore(str(work / "nestor.db"))
    store.init_db()
    store.memory_init()
    storage.set_store(store)

    print(f"\n{BOLD}jeles sources → nestor{OFF}  "
          f"{DIM}{DOMAIN}→{TARGET}, read by parsing{OFF}")
    print(f"   {len(sources)} institution(s) declared")

    keyed = [k for k, v in sources.items() if v.get("key_required")]
    for key, spec in sources.items():
        src, tgt = claim(key, spec)
        hosts = ", ".join(spec.get("hosts") or []) or "none listed"
        memory.add_pair(src, tgt, DOMAIN, TARGET, status="draft",
                        origin=f"{ORIGIN}:{key}", store=store,
                        reason=(f"Declared hosts: {hosts}. "
                                f"key_required={bool(spec.get('key_required'))}. "
                                f"Whether it genuinely serves these subjects is a "
                                f"routing judgment no test makes."))

    # What a test already covers, said out loud so nobody seals it twice.
    print(f"   {DIM}key_required is checkable and {len(keyed)} declare it; hosts "
          f"are checkable. Subjects are not.{OFF}")

    # 1. Sources the router cannot tell apart.
    by_domains: dict[tuple, list[str]] = collections.defaultdict(list)
    for key, spec in sources.items():
        by_domains[tuple(sorted(spec.get("domain") or []))].append(key)
    twins = {d: ks for d, ks in by_domains.items() if len(ks) > 1}
    print(f"\n{BOLD}sources declaring identical subjects{OFF}  "
          f"{DIM}route_sources() cannot prefer one over the other{OFF}")
    if not twins:
        print("   none")
    for domains, keys in sorted(twins.items()):
        print(f"   {AMBER}{', '.join(keys):32}{OFF} {', '.join(domains)}")

    # 2. Host overlap. Not a defect — a note about how coarse the allow-list is.
    hosts = collections.Counter(h for v in sources.values() for h in (v.get("hosts") or []))
    shared = [(h, n) for h, n in hosts.most_common() if n > 1]
    print(f"\n{BOLD}hosts named by more than one source{OFF}  "
          f"{DIM}the egress allow-list is per source, the host is not{OFF}")
    for host, count in shared[:6]:
        print(f"   {count:2}x  {host}")
    print(f"   {DIM}{len(shared)} shared host(s) of {len(hosts)} — the "
          f"allow-list is tight, which is the honest reading.{OFF}")
    print(f"   {DIM}Granting one source's reach does grant a host others use, "
          f"but at this ratio that is a note,{OFF}")
    print(f"   {DIM}not a finding.{OFF}")

    # 3. Subjects served by exactly one source: a single point of failure for
    #    any question routed there.
    per_subject = collections.Counter(
        d for v in sources.values() for d in (v.get("domain") or []))
    alone = sorted(s for s, n in per_subject.items() if n == 1)
    print(f"\n{BOLD}subjects with exactly one source{OFF}  "
          f"{DIM}{len(alone)} of {len(per_subject)}{OFF}")
    print(f"   {', '.join(alone) if alone else 'none'}")
    # Both of the hypotheses this block used to raise have now been measured
    # against the checkout, and neither was right as written. Corrected in
    # place and visibly, per the standing rule: a claim that was acted on is
    # part of the record, and quietly deleting it would leave the reader of an
    # older run with no way to know it had been withdrawn.
    print(f"\n   {DIM}MEASURED: routing breadth only — a query tagged to one of "
          f"these fans out to one source.{OFF}")
    print(f"\n   {AMBER}Hypothesis 1, was 'unmeasured' — now CONFIRMED, and the "
          f"stated reason was wrong.{OFF}")
    print(f"   {DIM}It asked whether a single-sourced subject struggles to clear "
          f"the corroboration bar. It does,{OFF}")
    print(f"   {DIM}and not because coverage is narrow: jeles.verify._identity "
          f"reads citation['source'] FIRST,{OFF}")
    print(f"   {DIM}and sources._result puts the REGISTRY KEY there (all 69 call "
          f"sites, 65 constants). So the{OFF}")
    print(f"   {DIM}per-record institution each adapter assembles is never "
          f"counted. One adapter returning five{OFF}")
    print(f"   {DIM}different institutions counts as one. Measured: "
          f"['openalex'] -> single_source. jeles#53.{OFF}")
    print(f"\n   {RED}Hypothesis 2, was 'unmeasured' — now FALSIFIED, and it was "
          f"wrong in the OPPOSITE direction.{OFF}")
    print(f"   {DIM}It said 9 sources list doi.org and registrable_domain() "
          f"collapses them, so nine institutions{OFF}")
    print(f"   {DIM}could corroborate as one. That cannot happen for registry "
          f"output: the site is only a{OFF}")
    print(f"   {DIM}FALLBACK for a citation with no label, and _result always "
          f"sets one. Measured — two doi.org{OFF}")
    print(f"   {DIM}citations from different adapters keep distinct keys "
          f"('openalex', 'core'). The real error runs{OFF}")
    print(f"   {DIM}the other way: two adapters carrying the SAME institution "
          f"read as corroborated.{OFF}")

    # Write the measured findings to a file if asked.  Before this flag
    # existed, these findings lived only in stdout and every reader
    # re-derived or misread them privately (IDEAS 6.104).
    if args.findings:
        md = format_findings(
            n_sources=len(sources),
            n_keyed=len(keyed),
            twins=twins,
            shared=shared,
            n_hosts=len(hosts),
            alone=alone,
            n_subjects=len(per_subject),
        )
        out = pathlib.Path(args.findings)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(md, encoding="utf-8")
        print(f"\n   {GREEN}findings written → {out}{OFF}")

    sealed = sum(1 for r in store.memory_candidates(DOMAIN, TARGET)
                 if r["status"] == "sealed")
    print(f"\n{BOLD}what is in the store{OFF}")
    print(f"   {len(sources)} row(s), {AMBER}{sealed} sealed{OFF}")
    print(f"   {DIM}Every row is a draft, and this is the corpus where that "
          f"matters most:{OFF}")
    print(f"   {DIM}a source verified today can be wrong by autumn without "
          f"anybody touching the row.{OFF}")

    if args.keep:
        print(f"\n   {DIM}kept: {work}{OFF}\n")
    else:
        shutil.rmtree(work, ignore_errors=True)
        print()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
